"""followers

Revision ID: 057098cdb198
Revises: 8212f0511641
Create Date: 2023-11-27 20:19:55.599149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '057098cdb198'
down_revision = '8212f0511641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
